import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/widgets/header";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Electric Cars, Solar & Clean Energy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <main>
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
